name: cloud_certify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  lottie: ^3.3.1
  pinput: ^5.0.1

  # State Management
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  # Storage
  get_storage: ^2.1.1
  firebase_storage: ^12.4.4

  # Network
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.4.1
  http:

  # Firebase
  firebase_auth: ^5.4.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # Utilities
  package_info_plus: ^8.0.0
  device_info_plus: ^11.3.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  csv: ^6.0.0
  intl: 
  form_field_validator: ^1.1.0
  logging: ^1.3.0
  go_router: ^14.8.1
  shared_preferences: ^2.5.2

  # Data Grid
  syncfusion_flutter_datagrid: ^28.2.11
  syncfusion_flutter_core: ^28.2.11

  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^7.7.0

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.7
  loading_animation_widget: ^1.3.0
  responsive_framework: ^1.5.1
  animate_do: ^4.2.0
  freezed_annotation: ^2.4.4
  hugeicons: ^0.0.10
  flutter_html: ^3.0.0
  built_collection: ^5.1.1
  built_value: ^8.9.5
  percent_indicator: ^4.2.5
  wiredash: ^2.4.0
  firebase_analytics: ^11.4.5
  toastification: ^3.0.2
  flutter_markdown: ^0.7.7
  animated_loading_border: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^3.1.0

  # Code Generation
  go_router_builder: ^2.7.1
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  openapi_generator: ^6.1.0
  openapi_generator_cli: ^6.1.0
  openapi_generator_annotations: ^6.1.0


  # API Client
  cloud_certify_service_api:
    path: api/cloud_certify_service_api


flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/json/
    - assets/social/
    - assets/svg/
    - assets/png/
    - assets/test_stats/
    - assets/
    - fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: fonts/Outfit-Bold.ttf
          weight: 700
        - asset: fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/Outfit-Regular.ttf
          weight: 400
        - asset: fonts/Outfit-Light.ttf
          weight: 300